CREATE TABLE Ambient 
	(id INTEGER PRIMARY KEY AUTOINCREMENT,
	Temperature REAL NOT NULL,
	Humidity REAL NOT NULL,
	Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE Report 
    (id INTEGER PRIMARY KEY AUTOINCREMENT,
    ReportName TEXT NOT NULL UNIQUE,
	StartDate TIMESTAMP NOT NULL,
	StopDate TIMESTAMP NOT NULL,
    Temperature INTEGER NOT NULL,
    Humidity INTEGER NOT NULL,
	Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP)